# Based on:
# https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
# https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push image
        run: make deploy
